#pragma once

#ifndef ROCOCO_UE5_EXPORT
# ifdef ROCOCO_BUILD_IS_MONOLITHIC
#  define ROCOCO_UE5_EXPORT
#  define ROCOCO_UE5_IMPORT
# else
#  define ROCOCO_UE5_EXPORT DLLEXPORT
#  define ROCOCO_UE5_IMPORT DLLIMPORT
# endif
#endif

#define _ROCOCO_WIDECHAR_ WIDECHAR

#ifdef PLATFORM_ANDROID
# define ROCOCO_WIDECHAR_IS_CHAR_16_T
#endif

#ifdef _WIN32
# define ROCOCO_WIDECHAR_IS_WCHAR_T
#endif

#ifndef ROCOCO_API
# define ROCOCO_API			ROCOCO_UE5_IMPORT
#endif

#define ROCOCO_WINDOWS_API  ROCOCO_UE5_IMPORT
#define ROCOCO_UTIL_API		ROCOCO_UE5_IMPORT
#define SEXYUTIL_API		ROCOCO_UE5_IMPORT
#define SCRIPTEXPORT_API	ROCOCO_UE5_IMPORT
#define ROCOCO_SEXML_API	ROCOCO_UE5_IMPORT
#define SEXYUTIL_API		ROCOCO_UE5_IMPORT
#define ROCOCO_JPEG_API     ROCOCO_UE5_IMPORT
#define ROCOCO_TIFF_API     ROCOCO_UE5_IMPORT
#define ROCOCO_GUI_API		ROCOCO_UE5_IMPORT

#ifndef ROCOCO_GUI_RETAINED_API
# define ROCOCO_GUI_RETAINED_API ROCOCO_UE5_IMPORT
#endif

#ifndef ROCOCO_GREAT_SEX_API
# define  ROCOCO_GREAT_SEX_API ROCOCO_UE5_IMPORT
#endif

#define ROCOCO_USE_SAFE_V_FORMAT
